name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff (lint)
        run: |
          ruff --version
          # Verificação de qualidade (sem auto-fix)
          ruff check .

      - name: Run tests (pytest se existir, senão unittest)
        run: |
          if python - <<'PY'
import importlib.util, sys
spec = importlib.util.find_spec("pytest")
sys.exit(0 if spec else 1)
PY
          then
            pytest -q
          else
            python -m unittest -v
          fi

      - name: Upload test results (logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            ./.ruff_cache
            **/.pytest_cache
          if-no-files-found: ignore
