name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # garante ruff/pytest mesmo se não estiverem no requirements
          pip install --upgrade ruff pytest

      - name: Ruff (lint)
        run: ruff check .

      - name: Run tests
        run: |
          if python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('pytest') else 1)"; then
            pytest -q
          else
            python -m unittest -v
          fi

      - name: Upload test results (logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            .ruff_cache
            **/.pytest_cache
          if-no-files-found: ignore
